spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-microservice:
  greeting: "Hello Everybody"
  default-value: "It´s good to see you again!"
